- hosts: all 
  become_user: root
  become: true
  gather_facts: false

  pre_tasks:

  - name: Bootstrap with python
    raw: which python || (sudo apt update; sudo apt install -y python; sudo yum install -y python)
    ignore_errors: yes


  - name: Instalando EPEL
    raw:  sudo yum install -y  epel-release
    ignore_errors: yes 

  - name: Instalando Ansible # Modo nao bonito
    raw: sudo yum install -y ansible
    ignore_errors: yes

  - name: Gathering Facts
    setup: 

  tasks:
  - copy: 
      src: /vagrant/arquivos/virt7-docker-common-release.repo 
      dest: /etc/yum.repos.d/virt7-docker-common-release.repo 

  - name: Disable SElinux permanetly
    lineinfile: dest=/etc/selinux/config state=present create=no regexp='SELINUX=.*' line='SELINUX=disabled'

  - name: Set SELinux in permissive mode until the machine is rebooted
    shell: setenforce 0
    ignore_errors: True

  - name: Desliga SELinux
    selinux:  state=disabled


  - name: yum-clean-metadata
    command: yum clean metadata
    args:
       warn: no

  - name: Instalando atualizacoes SO - Centos 
    yum: name=* state=latest update_cache=yes
    when: ansible_distribution == "CentOS"
    tags: atualizar

  - name: Instalado Pacotes 
    action: "{{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes"
    with_items:
     - ansible
     - python-pip 
     - python-jinja2
     - sshpass
     - openssh-clients
     - libselinux-python
     - net-tools
     - vim
     - sudo
     - wget
     - ntpdate
     - rcs 
     - curl
     - sysstat
     - wget
     - kubernetes 
     - flannel
    tags: instalar

  - name: Desabilitando servicos 
    service: name={{ item }} enabled=no
    with_items:
     - firewalld
    tags: servico 

  - name: Desabilitando servicos 
    service: name={{ item }} state=stopped
    with_items:
     - firewalld
    tags: servico 

